#!/bin/bash

# script/docker
#
# Run command in development container

set -euo pipefail

cd "$(dirname "$0")/.."

docker run --rm -ti -u ubuntu \
    -v "$(pwd)":/home/ubuntu/workspace \
    -v /tmp:/tmp \
    -w /home/ubuntu/workspace \
    giomba/ceda-cemu-builder:3 \
    "$@"
