#!/bin/bash

set -euo pipefail

CLANG_FORMAT_OPTS=()

while getopts "n" opts; do
    case "${opts}" in
        n)
            CLANG_FORMAT_OPTS=(-n -Werror)
            ;;
    esac
done

shopt -s globstar
clang-format -i "${CLANG_FORMAT_OPTS[@]}" src/**/*.[ch]

