name: 'Build'

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: giomba/ceda-cemu-builder:1
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Software quality
        run: |
          script/format -n
      - name: Build
        run: |
          git config --global --add safe.directory /__w/ceda-cemu/ceda-cemu
          git submodule init
          git submodule update
          script/build release
          script/build debug
      - name: Test
        run: |
          build/release/ceda-test

